apiVersion: apps/v1
kind: Deployment
metadata:
  name: goormi-web
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: goormi-fargate
  template:
    metadata:
      labels:
        app: goormi-fargate
