apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/goormi_web
  newName: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/goormi_web
  newTag: goormi
- name: 454457097752.dkr.ecr.ap-northeast-2.amazonaws.com/goormi_web
  newName: 454457097752.dkr.ecr.ap-northeast-2.amazonaws.com/goormi_web
  newTag: a291763f
resources:
- ../../base
patchesStrategicMerge:
- deploy-patch.yaml
- service-patch.yaml
